//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medsoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTracking
    {
        public int PulseValue { get; set; }
        public int Temperature { get; set; }
        public System.DateTime MeasurementDate { get; set; }
        public string Status { get; set; }
        public System.Guid HistoryId { get; set; }
    
        public virtual History History { get; set; }
    }
}
