//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medsoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Alarms = new HashSet<Alarm>();
            this.Patients = new HashSet<Patient>();
        }
    
        public System.Guid DoctorId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Function { get; set; }
        public string Hospital { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual ICollection<Alarm> Alarms { get; set; }
        public virtual Identity Identity { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
