//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medsoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public History()
        {
            this.ActivityTrackings = new HashSet<ActivityTracking>();
        }
    
        public System.Guid HistoryId { get; set; }
        public System.Guid MedicalReportId { get; set; }
    
        public virtual ICollection<ActivityTracking> ActivityTrackings { get; set; }
        public virtual MedicalReport MedicalReport { get; set; }
    }
}
