//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medsoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identity
    {
        public Identity()
        {
            this.Doctors = new HashSet<Doctor>();
            this.Patients = new HashSet<Patient>();
        }
    
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
