//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medsoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalReport
    {
        public MedicalReport()
        {
            this.Histories = new HashSet<History>();
            this.Patients = new HashSet<Patient>();
            this.Recomandations = new HashSet<Recomandation>();
        }
    
        public System.Guid MedicalReportId { get; set; }
        public string Allergies { get; set; }
        public string Diagnostic { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<Recomandation> Recomandations { get; set; }
    }
}
