//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public System.Guid AddressId { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> StreetNumber { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> PostalCode { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
