//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedsoftEntities : DbContext
    {
        public MedsoftEntities()
            : base("name=MedsoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Alarm> Alarms { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MedicalReport> MedicalReports { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Recomandation> Recomandations { get; set; }
        public virtual DbSet<ActivityTracking> ActivityTrackings { get; set; }
    }
}
