//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public System.Guid PatientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CNP { get; set; }
        public string Job { get; set; }
        public string Preoffession { get; set; }
        public System.Guid AddressId { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string PhoneNumber { get; set; }
        public System.Guid MedicalReportId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid DoctorId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Login Login { get; set; }
        public virtual MedicalReport MedicalReport { get; set; }
    }
}
