//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recomandation
    {
        public System.Guid RecomandationId { get; set; }
        public string RecomandationType { get; set; }
        public string Duration { get; set; }
        public string Other { get; set; }
        public System.Guid MedicalReportId { get; set; }
    
        public virtual MedicalReport MedicalReport { get; set; }
    }
}
